# Colors
[colors.primary]
foreground = "#f9efc5"
background = "#191b29"
dim_foreground = "#25272e"
# This is only used when draw_bold_text_with_bright_colors is enabled.
bright_foreground = "None"

[colors.normal]
black = "#14151f"
red = "#ff5f3b"
green = "#9ea32a"
yellow = "#ffb833"
blue = "#6e9685"
magenta = "#8db885"
cyan = "#67c4bd"
white = "#fbf1c7"

[colors.bright]
black = "#14151f"
red = "#eb3040"
green = "#988921"
yellow = "#eb8d27"
blue = "#5e8d6f"
magenta = "#85ab71"
cyan = "#58b69e"
white = "#fbf1c7"

[colors.dim]
black = "#14151f"
red = "#f76f63"
green = "#a3a559"
yellow = "#f6c55b"
blue = "#919c96"
magenta = "#a6bba0"
cyan = "#89c5bf"
white = "#fbf1c7"
